//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfLoadTest.WcfServiceClient {
    
    
    #region Component Designer generated code 
    public partial class ConfigLoader_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::WcfLoadTest.WcfServiceClient.@__ConfigLoader.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::WcfLoadTest.WcfServiceClient.ConfigLoader), typeof(global::WcfLoadTest.WcfServiceClient.ConfigLoader_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::WcfLoadTest.WcfServiceClient.ConfigLoader), typeof(global::WcfLoadTest.WcfServiceClient.ConfigLoader_))]
    internal sealed partial class @__ConfigLoader : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__ConfigLoader(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::WcfLoadTest.WcfServiceClient.@__ConfigLoader.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ConfigLoader);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Load", "Load0", "()V"));
            return methods;
        }
        
        private static void Load0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::WcfLoadTest.WcfServiceClient.ConfigLoader.Load();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::WcfLoadTest.WcfServiceClient.@__ConfigLoader(@__env);
            }
        }
    }
    #endregion
}
