// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package wcfloadtest.wcfserviceclient;

@net.sf.jni4net.attributes.ClrType
public class ConfigLoader extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected ConfigLoader(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected ConfigLoader() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void Load();
    
    public static system.Type typeof() {
        return wcfloadtest.wcfserviceclient.ConfigLoader.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        wcfloadtest.wcfserviceclient.ConfigLoader.staticType = staticType;
    }
    //</generated-proxy>
}
