//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfLoadTest.WcfServiceClientPublic.ServiceReferenceBasicHttp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBasicHttp.IServiceBasicHttp")]
    public interface IServiceBasicHttp {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBasicHttp/Init", ReplyAction="http://tempuri.org/IServiceBasicHttp/InitResponse")]
        void Init();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBasicHttp/LoadFileAndReturnFileSizeInBytes", ReplyAction="http://tempuri.org/IServiceBasicHttp/LoadFileAndReturnFileSizeInBytesResponse")]
        long LoadFileAndReturnFileSizeInBytes(System.IO.Stream file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBasicHttp/GetFileBySize", ReplyAction="http://tempuri.org/IServiceBasicHttp/GetFileBySizeResponse")]
        System.IO.Stream GetFileBySize(int fileSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBasicHttp/GetFileSizes", ReplyAction="http://tempuri.org/IServiceBasicHttp/GetFileSizesResponse")]
        int[] GetFileSizes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBasicHttp/GetIntValue", ReplyAction="http://tempuri.org/IServiceBasicHttp/GetIntValueResponse")]
        int GetIntValue(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBasicHttpChannel : WcfLoadTest.WcfServiceClientPublic.ServiceReferenceBasicHttp.IServiceBasicHttp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBasicHttpClient : System.ServiceModel.ClientBase<WcfLoadTest.WcfServiceClientPublic.ServiceReferenceBasicHttp.IServiceBasicHttp>, WcfLoadTest.WcfServiceClientPublic.ServiceReferenceBasicHttp.IServiceBasicHttp {
        
        public ServiceBasicHttpClient() {
        }
        
        public ServiceBasicHttpClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBasicHttpClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBasicHttpClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBasicHttpClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Init() {
            base.Channel.Init();
        }
        
        public long LoadFileAndReturnFileSizeInBytes(System.IO.Stream file) {
            return base.Channel.LoadFileAndReturnFileSizeInBytes(file);
        }
        
        public System.IO.Stream GetFileBySize(int fileSize) {
            return base.Channel.GetFileBySize(fileSize);
        }
        
        public int[] GetFileSizes() {
            return base.Channel.GetFileSizes();
        }
        
        public int GetIntValue(int value) {
            return base.Channel.GetIntValue(value);
        }
    }
}
