//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfLoadTest.WcfServiceClientPublic.ServiceReferenceNetTcp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceNetTcp.IServiceNetTcp")]
    public interface IServiceNetTcp {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNetTcp/Init", ReplyAction="http://tempuri.org/IServiceNetTcp/InitResponse")]
        void Init();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNetTcp/LoadFileAndReturnFileSizeInBytes", ReplyAction="http://tempuri.org/IServiceNetTcp/LoadFileAndReturnFileSizeInBytesResponse")]
        long LoadFileAndReturnFileSizeInBytes(System.IO.Stream file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNetTcp/GetFileBySize", ReplyAction="http://tempuri.org/IServiceNetTcp/GetFileBySizeResponse")]
        System.IO.Stream GetFileBySize(int fileSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNetTcp/GetFileSizes", ReplyAction="http://tempuri.org/IServiceNetTcp/GetFileSizesResponse")]
        int[] GetFileSizes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceNetTcp/GetIntValue", ReplyAction="http://tempuri.org/IServiceNetTcp/GetIntValueResponse")]
        int GetIntValue(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceNetTcpChannel : WcfLoadTest.WcfServiceClientPublic.ServiceReferenceNetTcp.IServiceNetTcp, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceNetTcpClient : System.ServiceModel.ClientBase<WcfLoadTest.WcfServiceClientPublic.ServiceReferenceNetTcp.IServiceNetTcp>, WcfLoadTest.WcfServiceClientPublic.ServiceReferenceNetTcp.IServiceNetTcp {
        
        public ServiceNetTcpClient() {
        }
        
        public ServiceNetTcpClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceNetTcpClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNetTcpClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceNetTcpClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Init() {
            base.Channel.Init();
        }
        
        public long LoadFileAndReturnFileSizeInBytes(System.IO.Stream file) {
            return base.Channel.LoadFileAndReturnFileSizeInBytes(file);
        }
        
        public System.IO.Stream GetFileBySize(int fileSize) {
            return base.Channel.GetFileBySize(fileSize);
        }
        
        public int[] GetFileSizes() {
            return base.Channel.GetFileSizes();
        }
        
        public int GetIntValue(int value) {
            return base.Channel.GetIntValue(value);
        }
    }
}
